name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with Ruff
        run: poetry run ruff check src tests
      - name: Test with pytest
        run: poetry run pytest
      - name: Build Docker image
        if: github.event_name == 'push'
        run: docker build -t universal-recommender .
      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: https://github.com/Marsupilami-it/UniRec
          tags: latest
          push: true