FROM confluentinc/cp-zookeeper:latest

# Переменные окружения
ENV ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
ENV ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}

# Volume для хранения данных Zookeeper
VOLUME /data/zookeeper